---
# Can't use for serverspec validation as we can't change resolv.conf in docker during play. DNS server will not be updated.

driver:
  name: docker
  ## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # require_chef_omnibus: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7
  # - name: alpine-3.7

suites:
  - name: default
    run_list:
    attributes:
