---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
#  env_vars:
#    ANSIBLE_KEEP_REMOTE_FILES: 1

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
## rpz format different
#  - name: ubuntu-12.04
  - name: centos-7
## FIXME! v2.2: template module failure/redhat
#    provisioner:
#      ansible_version: 2.1.2.0
#  - name: centos-6
#    provisioner:
#      ansible_version: 2.1.2.0
## FIXME! 'Installing Chef Omnibus to install busser to run tests' not supported = can disable
##	' sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)\nOSError: [Errno 2] No such file or directory'
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-zones
    run_list:
    attributes:
  - name: default-ansible20
    run_list:
    includes:
      - ubuntu-16.04
#      - ubuntu-14.04
#      - centos-7
#      - centos-6
    provisioner:
## 1.9.6.0 NOK as blockinfile module or include manually https://github.com/yaegashi/ansible-role-blockinfile
#      ansible_version: 1.9.6.0
      ansible_version: 2.0.0.2
      name: ansible_playbook
      playbook: test/integration/default/default.yml
