---

- name: Debug | var ansible_all_ipv4_addresses
  ansible.builtin.debug: var=ansible_all_ipv4_addresses
- name: check network config
  ansible.builtin.command: "ifconfig -a"
  register: ifconfig
  changed_when: false
- name: Debug | var ifconfig
  ansible.builtin.debug: var=ifconfig.stdout_lines
- name: redhat | check network config 2
  ansible.builtin.command: "ls -al /etc/sysconfig/network-scripts/"
  register: netdir
  changed_when: false
  failed_when: false
- name: Debug | var network-scripts
  ansible.builtin.debug: var=netdir.stdout_lines

- name: check if file exists
  ansible.builtin.stat: path=/etc/sysconfig/network-scripts/ifcfg-eth0
  register: ifcfg
- name: redhat | ensure ifcfg-eth0 has localhost resolver
  ansible.builtin.blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      PEERDNS=no
      DNS1=127.0.0.1
    marker: "# {mark} ANSIBLE MANAGED BLOCK: local dns"
  # notify:
  #   - restart network
  when: ifcfg.stat.exists

- name: redhat | ensure bind active
  ansible.builtin.service: name={{ bind_svc }} state=started
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: check if file exists
  ansible.builtin.stat: path=/etc/resolv.conf
  register: resolvconf
- name: redhat | direct change of /etc/resolv.conf to avoid restarting network
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    regexp: '^nameserver .*'
    line: 'nameserver 127.0.0.1'
    insertafter: '; generated by '
  when: resolvconf.stat.exists
  failed_when: "{{ bind_resolvconf_update_failedwhen | default(omit) }}"
