---

- debug: var=ansible_all_ipv4_addresses
- name: check network config
  command: "ifconfig -a"
  register: ifconfig
  changed_when: false
- debug: var=ifconfig.stdout_lines
- name: redhat | check network config 2
  command: "ls -al /etc/sysconfig/network-scripts/"
  register: netdir
  changed_when: false
- debug: var=netdir.stdout_lines

- name: check if file exists
  stat: path=/etc/sysconfig/network-scripts/ifcfg-eth0
  register: ifcfg
- name: redhat | ensure ifcfg-eth0 has localhost resolver
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      PEERDNS=no
      DNS1=127.0.0.1
    marker: "# {mark} ANSIBLE MANAGED BLOCK: local dns"
  # notify:
  #   - restart network
  when: ifcfg.stat.exists

- name: redhat | ensure bind active
  service: name={{ bind_svc }} state=started

- name: check if file exists
  stat: path=/etc/resolv.conf
  register: resolvconf
- name: redhat | direct change of /etc/resolv.conf to avoid restarting network
  lineinfile:
    dest: /etc/resolv.conf
    regexp: '^nameserver .*'
    line: 'nameserver 127.0.0.1'
    insertafter: '; generated by '
  when: resolvconf.stat.exists
