---
## for haveged (better entropy for gpg)
#- include: redhat-epel.yml

- name: yum | Install bind
  yum: name={{ item }} state=present update_cache=yes
  with_items: "{{ bind_pkgs }}"

## necessary for 'named-checkconf -t /var/named/chroot/ /etc/named.conf'
- name: yum | copy file in chroot
  copy: "src={{ item.s }} dest={{ item.d }} remote_src=yes mode=0640 group={{ bind_user }}"
  with_items:
    - { s: /etc/named.rfc1912.zones, d: "{{ bind_etc }}/named.rfc1912.zones" }
    - { s: /etc/named.root.key, d: "{{ bind_etc }}/named.root.key" }
#    - { s: /var/named/named.ca, d: /var/named/chroot/var/named }
    - { s: /var/named/named.ca, d: "{{ bind_etc }}" }
    - { s: /var/named/named.localhost, d: /var/named/chroot/var/named }
    - { s: /var/named/named.loopback, d: /var/named/chroot/var/named }
    - { s: /var/named/named.empty, d: /var/named/chroot/var/named }

- name: ensure conf working in/out of chroot
  file: src=/ dest=/var/named/chroot/var/named/chroot state=link

- name: ensure named-chroot required directories exist
  file: dest={{ item }} state=directory owner=named group=named mode=0755
  with_items:
    - /var/named/chroot/var/named/dynamic
    - /var/named/chroot/var/named/data

- name: ensure named service is disable - using named-chroot
  service: name=named state=stopped enabled=no

## http://kb.odin.com/en/120844
## mknod: ‘/var/named/chroot/dev/random’: Operation not permitted
#- name: create entropy source inside chroot to avoid warning
#  command: "mknod /var/named/chroot/dev/random c 1 8 creates=/var/named/chroot/dev/random"

- name: redhat | update default configuration
  template:
     src: named-rhel.conf.j2
     dest: "{{ bind_etc }}/named.conf"
     mode: '0640'
     owner: root
     group: "{{ bind_user }}"
     backup: yes
  notify:
    - restart bind
