---

## To ensure dnssec/zones tests always succeed, resolv.conf should only contain localhost...
- name: debian | ensure /etc/resolv.conf as only localhost resolver
  replace:
    dest: /etc/resolv.conf
    regexp: 'nameserver .*'
    replace: 'nameserver 127.0.0.1'
  failed_when: false
