---
## inspired from
## https://www.sbarjatiya.com/notes_wiki/index.php/Ansible_named-server_role_for_both_public_and_private_DNS
##      https://github.com/bertvv/ansible-role-bind/tree/master

- name: Create zone forward files
  ansible.builtin.template:
    src: "forward.zone.j2"
    dest: "{{ bind_etc }}/db.{{ item }}.zone"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
    validate: "named-checkzone {{ item }} %s"
  with_items:
    - "{{ zone.vars.bind_zone_name }}"
  notify:
    - Restart bind
  when:
    - zone.vars.bind_zone_type != 'secondary'

- name: Create reverse zone files
  ansible.builtin.template:
    src: "reverse.zone.j2"
    # dest: "{{ bind_etc }}/db.rev.{{ item|reverse_lookup_zone }}.zone"
    dest: "{{ bind_etc }}/db.rev.{{ item | ansible.utils.ipaddr('revdns') | regex_replace('^\\d+\\.', '') }}zone"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
    # validate: "named-checkzone {{ item|reverse_lookup_zone }} %s"
    validate: "named-checkzone {{ item | ansible.utils.ipaddr('revdns') | regex_replace('^[0-9]+\\.', '') }} %s"
  with_items: "{{ zone.vars.bind_zone_networks }}"
  notify:
    - Restart bind
  when:
    - zone.vars.bind_zone_type != 'secondary'

- name: Debug | var bind_zone_name
  ansible.builtin.debug:
    var: zone.vars.bind_zone_name
- name: Ensure named.conf.local-zones present
  ansible.builtin.template:
    src: "named-zones.conf.local.j2"
    dest: "{{ bind_etc }}/named.conf.local-zone-{{ zone.vars.bind_zone_name }}"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
  notify:
    - Restart bind
