---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every monday 06:00
    - cron: '0 6 * * 1'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-${{ matrix.version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: ubuntu
            version: '24.04'
            suite: default
            experimental: false
          - distribution: ubuntu
            version: '22.04'
            suite: default
            experimental: false
          - distribution: ubuntu
            version: '20.04'
            suite: default
            experimental: false
          - distribution: ubuntu
            version: '24.04'
            suite: default-bind-dnscrypt
            experimental: false
          - distribution: ubuntu
            version: '24.04'
            suite: default-dnscrypt-bind
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.bind
      ANSIBLE_SUITE: ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml || true
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh || true
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: verify
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/hosts
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status bind9 || true
          systemctl -l --no-pager status bind || true
          systemctl -l --no-pager status named || true
          systemctl -l --no-pager status dnscrypt-proxy || true
          systemd-analyze --no-pager security || true
          systemd-analyze --no-pager security named || true
          systemctl --failed || true
          rsyslogd -v
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl
        run: |
          journalctl -l --no-pager -u named || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - etc
        run: |
          set -x
          ls -la /etc/bind9/ || true
          ls -la /etc/bind/ || true
          ls -la /etc/named/ || true
          sudo cat /etc/named/named.conf || true
          sudo cat /etc/named/named.conf.local || true
          sudo cat /etc/named/named.conf.options || true
          sudo cat /etc/bind/named.conf || true
          sudo cat /etc/bind/named.conf.local || true
          sudo cat /etc/bind/named.conf.options || true
          sudo named-checkconf -pxzj /etc/bind/named.conf || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - dig
        run: |
          set -x
          dig @127.0.0.1 -c CH -t txt version.bind
          dig_args="+noall +question +answer"
          for ns in 127.0.0.1 127.0.0.2; do
            echo "== ns: ${ns}"
            dig ${dig_args} @${ns} www.google.com
            dig ${dig_args} @${ns} archive.ubuntu.com
            dig ${dig_args} @${ns} download.falco.org
            dig ${dig_args} @${ns} apt.grafana.com
            dig ${dig_args} @${ns} artifacts.elastic.co
            dig ${dig_args} @${ns} ns.internal
            dig ${dig_args} @${ns} mail.internal
            dig ${dig_args} @${ns} host2.internal
            dig ${dig_args} @${ns} 192.168.1.1
            dig ${dig_args} @${ns} 192.168.1.2
            dig ${dig_args} @${ns} 192.168.1.3
          done
          dig +trace download.falco.org
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          set -x
          ls -la /var/log/named/ || true
          sudo tail -100 /var/log/named/*
          ls -la /var/log/bind/ || true
          sudo tail -100 /var/log/bind/*
          sudo tail -100 /var/log/syslog
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - apparmor
        run: |
          set -x
          find /etc/apparmor.d/ -iname '*named*' -ls
          cat /etc/apparmor.d/usr.sbin.named
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - dnscrypt
        run: |
          set -x
          sudo cat /opt/dnscrypt-proxy2/linux-x86_64/forwarding-rules.txt || true
          ls -l /var/log/dnscrypt*.log || true
          sudo tail -100 /var/log/dnscrypt*.log || true
        if: ${{ always() }}
        continue-on-error: true
